dataset:
  batch_size: 100
  num_workers: 8
  num_of_cal_data_per_class: 50 # number of calibration data per class
  num_classes: 7 # number of classes
  path: /root/autodl-tmp # path to store datasets
  name: PACS

seed: 120
device: cuda:0